version: '2'

services:
    api:
      image: rlugo14/fkbosna-service
      restart: always
      depends_on: [db]
      ports:
        - 3005:3005
      environment:
        PORT: 3005
        JWT_SECRET: C3or6grFVevY61IiAv4S
        DATABASE_URL: mysql://raul:OREQ1VPn08Fl6UWEgHnI@db/fkbosna
    
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - "./data.sql:/docker-entrypoint-initdb.d/data.sql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: fkbosna
        MYSQL_USER: raul
        MYSQL_PASSWORD: OREQ1VPn08Fl6UWEgHnI
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080